name: Cass Operator Build & Deploy
on:
  push:
    branches: [ multiarch ]
jobs:
  build_operator_docker:
    name: Build Cass Operator Docker Image
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      GOROOT: /usr/local/go1.13
    steps:
      - uses: actions/checkout@v2
      - name: Setup Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          version: latest
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build docker
        run: |
          docker buildx build \
            --push \
            --platform linux/amd64,linux/arm64 \
            --tag johntrimble/cass-operator-multiarch:latest \
            --file operator/docker/base/Dockerfile \
            ./
